baseURL: https://blog.bbjc.cc/
languageCode: zh-cn
title: bbjcz's  blogs
theme: "PaperMod"
params:
  ShowCodeCopyButtons: true
menu:
  main:
  - name: B站主页
    url: https://space.bilibili.com/352110790